name: Generate Man Page

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build-manpage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      - name: Generate man page
        run: |
          mkdir -p man
          pandoc -s -t man README.org -o man/tlbx.1
          echo "Man page generated successfully"
          man ./man/tlbx.1 || true  # Preview (continues if fails)

      - name: Upload man page artifact
        uses: actions/upload-artifact@v4
        with:
          name: tlbx-manpage
          path: man/tlbx.1
          retention-days: 1  # Keeps artifact for 1 day (adjust as needed)

