name: Generate and Commit Man Page

on:
  push:
    paths:
      - 'README.org'
      - '.github/workflows/**'
  workflow_dispatch:

permissions:
  contents: write  # needed to push commits

jobs:
  build-manpage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install pandoc
        run: sudo apt update && sudo apt install -y pandoc

      - name: Generate man page
        run: |
          mkdir -p manpages
          pandoc -s -t man README.org -o manpages/tlbx.1

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and push man page
        run: |
          git add manpages/tlbx.1
          git diff --cached --quiet || git commit -m "Update man page from tlbx.org"
          git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload manpage artifact
        uses: actions/upload-artifact@v3
        with:
          name: tlbx-manpage
          path: manpages/tlbx.1

  download-artifact:
    runs-on: ubuntu-latest
    needs: build-manpage
    steps:
      - name: Download the man page artifact
        uses: actions/download-artifact@v3
        with:
          name: tlbx-manpage

      - name: Extract the downloaded artifact
        run: |
          mkdir -p downloaded-manpages
          mv tlbx-manpage/tlbx.1 downloaded-manpages/tlbx.1
