# .github/workflows/shellcheck.yml

name: Shellcheck Script

on:
  push:
    branches: [ main ] # Adjust branch name if necessary
  pull_request:
    branches: [ main ] # Adjust branch name if necessary
  workflow_dispatch: # Add this line to enable manual triggering

jobs:
  shellcheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install shellcheck
      run: |
        sudo apt-get update
        sudo apt-get install -y shellcheck

    - name: Run shellcheck on drdr
      run: shellcheck tlbx
